<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="8" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="13577" started-at="2022-08-13T11:06:13Z" finished-at="2022-08-13T11:06:26Z">
    <groups>
      <group name="@smoke">
        <method signature="Testing2.tc0()[pri:0, instance:org.login.Testing2@6574b225]" name="tc0" class="org.login.Testing2"/>
        <method signature="Testing2.tc04()[pri:0, instance:org.login.Testing2@6574b225]" name="tc04" class="org.login.Testing2"/>
      </group> <!-- @smoke -->
      <group name="@retest">
        <method signature="Testing2.tc03()[pri:0, instance:org.login.Testing2@6574b225]" name="tc03" class="org.login.Testing2"/>
      </group> <!-- @retest -->
      <group name="@reg">
        <method signature="Testing2.tc01()[pri:0, instance:org.login.Testing2@6574b225]" name="tc01" class="org.login.Testing2"/>
        <method signature="Testing2.tc02()[pri:0, instance:org.login.Testing2@6574b225]" name="tc02" class="org.login.Testing2"/>
      </group> <!-- @reg -->
    </groups>
    <test name="Surefire test" duration-ms="13577" started-at="2022-08-13T11:06:13Z" finished-at="2022-08-13T11:06:26Z">
      <class name="org.login.Testing">
        <test-method status="PASS" signature="tc0(java.lang.String, java.lang.String)[pri:0, instance:org.login.Testing@5056dfcb]" name="tc0" duration-ms="6089" started-at="2022-08-13T11:06:13Z" data-provider="excelIntegration" finished-at="2022-08-13T11:06:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[aaa]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[bsahfaeugeu]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc0 -->
        <test-method status="PASS" signature="tc0(java.lang.String, java.lang.String)[pri:0, instance:org.login.Testing@5056dfcb]" name="tc0" duration-ms="3176" started-at="2022-08-13T11:06:19Z" data-provider="excelIntegration" finished-at="2022-08-13T11:06:22Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[FamousTamizha]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[bsahfaeugeu]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc0 -->
        <test-method status="PASS" signature="tc0(java.lang.String, java.lang.String)[pri:0, instance:org.login.Testing@5056dfcb]" name="tc0" duration-ms="3687" started-at="2022-08-13T11:06:22Z" data-provider="excelIntegration" finished-at="2022-08-13T11:06:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[FamousTamizha]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Famous987]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc0 -->
      </class> <!-- org.login.Testing -->
      <class name="org.login.Testing2">
        <test-method status="PASS" signature="tc0()[pri:0, instance:org.login.Testing2@6574b225]" name="tc0" duration-ms="1" started-at="2022-08-13T11:06:26Z" finished-at="2022-08-13T11:06:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc0 -->
        <test-method status="FAIL" signature="tc04()[pri:0, instance:org.login.Testing2@6574b225]" name="tc04" duration-ms="2" started-at="2022-08-13T11:06:26Z" finished-at="2022-08-13T11:06:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.login.Testing2.tc04(Testing2.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:192)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:93)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc04 -->
        <test-method status="PASS" signature="tc03()[pri:0, instance:org.login.Testing2@6574b225]" name="tc03" duration-ms="1" started-at="2022-08-13T11:06:26Z" finished-at="2022-08-13T11:06:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc03 -->
        <test-method status="SKIP" signature="tc02()[pri:0, instance:org.login.Testing2@6574b225]" name="tc02" duration-ms="0" depends-on-groups="@smoke" started-at="2022-08-13T11:06:26Z" finished-at="2022-08-13T11:06:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Testing2.tc02()[pri:0, instance:org.login.Testing2@6574b225] depends on not successfully finished methods in group "@smoke"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Testing2.tc02()[pri:0, instance:org.login.Testing2@6574b225] depends on not successfully finished methods in group "@smoke"
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:192)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:93)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc02 -->
        <test-method status="SKIP" signature="tc01()[pri:0, instance:org.login.Testing2@6574b225]" name="tc01" duration-ms="0" depends-on-groups="@smoke" started-at="2022-08-13T11:06:26Z" finished-at="2022-08-13T11:06:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Testing2.tc01()[pri:0, instance:org.login.Testing2@6574b225] depends on not successfully finished methods in group "@smoke"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Testing2.tc01()[pri:0, instance:org.login.Testing2@6574b225] depends on not successfully finished methods in group "@smoke"
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:151)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:192)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:93)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc01 -->
      </class> <!-- org.login.Testing2 -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
